# Матричный метод

Метод обратной матрицы — это метод, использующийся при решении СЛАУ в том случае, если число неизвестных равняется числу уравнений.

Матричный вид записи: $ A * X = B $
где $ А $ - матрица системы, $ X $ - столбец неизвестных, $ B $ - столбец свободных коэффициентов

In [2]:
import numpy as np

In [3]:
A = np.matrix('2 -4 3; 1 -2 4; 3 -1 5')
B = np.matrix('1; 3; 2')

Для решения найдём обратную матрицу для A, а затем умножим её на матрицу свободных коэффициентов

In [4]:
A_inv = np.linalg.inv(A)
X = A_inv * B
print(X)

[[-1.00000000e+00]
 [ 1.11022302e-16]
 [ 1.00000000e+00]]


# Метод Крамера
Для использования метода Крамера необходимо, чтобы определитель матрицы не был равен нулю.

$ det(A) ≠ 0 $

In [5]:
A = np.matrix('2 -4 3; 1 -2 4; 3 -1 5')
B = np.matrix('1; 3; 2')
det_A = round(np.linalg.det(A), 3)
print(det_A)

-25.0


$ det(A) = -25 $, значит, можно использовать метод Крамера


$ x_n = det(An) / det(A) $

In [6]:
for i in range(len(A)):
    A[:,i] = B
    det_Ax = round(np.linalg.det(A), 3)
    print(A)
    A = np.matrix('1 55 6; 2 5 1; -3 2 7')
    print(f'Определитель равен {det_Ax}')
    print(f'X = {det_Ax / det_A}')
    

[[ 1 -4  3]
 [ 3 -2  4]
 [ 2 -1  5]]
Определитель равен 25.0
X = -1.0
[[ 1  1  6]
 [ 2  3  1]
 [-3  2  7]]
Определитель равен 80.0
X = -3.2
[[ 1 55  1]
 [ 2  5  3]
 [-3  2  2]]
Определитель равен -692.0
X = 27.68
