# Матричный метод

Метод обратной матрицы — это метод, использующийся при решении СЛАУ в том случае, если число неизвестных равняется числу уравнений.

Матричный вид записи: $ A * X = B $
где $ А $ - матрица системы, $ X $ - столбец неизвестных, $ B $ - столбец свободных коэффициентов

In [16]:
import numpy as np

In [17]:
A = np.matrix('1 55 6; 2 5 1; -3 2 7')
B = np.matrix('4; 8; 1')

Для решения найдём обратную матрицу для A, а затем умножим её на матрицу свободных коэффициентов

In [18]:
A_inv = np.linalg.inv(A)
X = A_inv * B
print(X)

[[ 3.58756345]
 [-0.18147208]
 [ 1.7322335 ]]


# Метод Крамера
Для использования метода Крамера необходимо, чтобы определитель матрицы не был равен нулю.

$ det(A) ≠ 0 $

In [19]:
A = np.matrix('1 55 6; 2 5 1; -3 2 7')
B = np.matrix('4; 8; 1')
det_A = round(np.linalg.det(A), 3)
print(det_A)

-788.0


$ det(A) = -25 $, значит, можно использовать метод Крамера


$ x_n = det(An) / det(A) $

In [23]:
for i in range(len(A)):
    A[:,i] = B
    det_Ax = round(np.linalg.det(A), 3)
    print(A)
    A = np.matrix('1 55 6; 2 5 1; -3 2 7')
    print(f'Определитель равен {det_Ax}')
    print(f'X = {det_Ax / det_A}')
    

[[ 4 -4  3]
 [ 8 -2  4]
 [ 1 -1  5]]
Определитель равен 102.0
X = -0.12944162436548223
[[ 1  4  6]
 [ 2  8  1]
 [-3  1  7]]
Определитель равен 143.0
X = -0.1814720812182741
[[ 1 55  4]
 [ 2  5  8]
 [-3  2  1]]
Определитель равен -1365.0
X = 1.732233502538071
